### ISSUE TITLE
Feature Request: Change gamemode

### ISSUE THREAD

**Issue by Blastogasm** [cengelha/NomNom#12]
Does this editor allow one to change the mode from survival to another like normal mode? Also how does one copy the save folder in the manager to create a new one?

**Comment by cengelha** [comment]
No, you can't change the game mode. I haven't tried that for myself and therefore don't know whether this is a good idea respectively how things behave after the change.
Do you have any experience with it?

The manager doesn't copy any folders. It copies the data from the saves of a slot to another one. Either by writing them to the respective file or (for PS4) by writing it in the correct position within the file.

**Comment by Blastogasm** [comment]
Well when I read about the one that was used on nomansskymods.com I remember reading something about that being one of the features they were trying to implement so I was just curious if this one could do that since this one does have some other features the other doesn't.

**Comment by cengelha** [comment]
Changing the game mode isn't hard actually (just change the first value "F2P"/"Version" in the save file). Add/Subtract 512 for each step in this enum https://github.com/monkeyman192/MBINCompiler/blob/development/libMBIN/Source/NMS/GameComponents/GcGameMode.cs#L10
For example to change a save from Normal to Survival add 1024.

As I mentioned I don't know the consequences but I will put it on the roadmap and test it at a appropriate time and we will see how it turns out. If you want to try it on your own it would be great if you share your results/observations here :)

**Comment by MisterTarget** [comment]
I tried that...
I wanted to switch from Normal to Survival but it just wont work. The Game works fine but it seems like it just dont care and overwrite the game files with some backups i think. The game save file name also changes.

It would be great if you can take a look at that and maybe implement it in your Editor, i think many people really need that

**Comment by MisterTarget** [comment]
I did it! I finally managed to change my Gamemode! After long time fiddeling arround, **big shoutout to cengelha for helping**

For all the users who are playing thru the Xbox Gamepass:
- 1. Locate your Savefile C:\Users\YOURNAME\AppData\Local\Packages\HelloGames.NoMansSky_bs190hzg1sesy\SystemAppData\wgs\RANDOM LONG NUMBER\ANOTHER LONG NUMBER
This is your Save file, in there are 3 files. One ist the biggest, one is small and one is namend Container, we dont need the Container.

- 2. Open the big file with Notepad++ and at the top you see "F2P":NUMBER:"Win|Final"
The NUMBER is your Gamemode. In the Origins patch the Number for the Gamemodes are

Normal: 4638 | Survival: 5662 | Creative: 5150 | Permadeath: 6686

Change the Number to the Gamemode listed above and Save this File. Oh and do a **BACKUP** in case.
- 3. Open the small file in a Hex editor you prefer

Go to the 5. Byte and you should see a Number from 0-7. Change this Byte to the according number.

Normal: 01 | Creative: 02 | Survival: 03 | Permadeath: 05

- 4. Save this file and name it like the original one if its not already.
- 5. Put the files back into your Save game folder and voila you changed your Gamemode!
- 6. Its likely you have more folders there, one is for auto save and one is for Manual saves. Just do everything above in this folder too.

If you have trouble finding your savegame just load your savefile and Manual save it and Auto save it and look for the timestamp in the folder.

**Comment by Blastogasm** [comment]
I am actually about to attempt most of these now since I have finally gotten some free time around work. So, I will let you guys know how it goes for me in just a bit. But I would first like to say thanks for giving me the information so that I could attempt them.

**Comment by Blastogasm** [comment]
I managed to get it to work by following the steps provided by Mister target. Before that though I had managed to break the save file I did however have multiple backups to try it with so that helped a lot. I greatly appreciate the help and information though folks. So far everything has gone on smoothly. Thanks again!

**Comment by Mike-Blackwell** [comment]
Alert! Alert an update to the above procedure as of 4/24/21 is needed, please note that the values have changed from the Origin I did not have a Creative or Permadeath save so it is unknown "?" what the new value is.

**Large File values:**
Normal: 4645| Creative: 5150 ? | Survival: 5669 | Permadeath: 6686 ? | Expedition: 7205

**Small File values:**
Normal: 01 | Creative: 02 | Survival: 03 | Permadeath: 05 | Expedition: 06

It would be interesting since the current NOMNOM editor doesn't handle the Expedition file correctly as it changes the Expedition Savefile to reflect Permadeath savefile, if one changes the newly created Permadeath (Expedition) back to Expedition using the above procedure if it works???

**Comment by Mike-Blackwell** [comment]
Well I was able to confirm changing my original Expedition file that got changed to Permadeath (NOMNOM) back to Expedition with no problem (just be aware to pay attention to your timestamp as Xbox system may not have your latest updates showing) by updating the small file from "05" to "06" with one exception; I had completed the Expedition game play prior to messing around with NOMNOM and noticed that my previously completed badges were reset, but when I went to the QuickSilver merchant I it showed that items were available.. needs some more investigation.
