### ISSUE TITLE
No scrolling in Knowledge tab + bugs

### ISSUE THREAD

**Issue by skupfer** [cengelha/NomNom#30]
It looks like the Knowledge tab needs a scroll bar. Cannot view all elements,

**Comment by skupfer** [comment]
Milestones: 

- Èxtreme Survival cannot be achieved. Currently 1/10. Upon going to the next step, the Remaining/Promotion locked fields go hidden. I changed it to 29000 for a test, still at 1/10 (despite showing 10/10)
- Words Learned (hard to get to) doesn't change, despite deselecting -> selecting it in the knowledge tab. (I "learned" all via NMSS before but there it doesn't work properly, too)

Mode: Advanced
- JSON Editor still greyed out

**Comment by cengelha** [comment]
Thanks for reporting.

It's already known that the knowledge tab has some issues. This will be resolved in the [next planned release](https://github.com/cengelha/NomNom/blob/3.0.0.13-alpha.13/ROADMAP.md#alpha14---feature-polishing).

The JSON editor is planned for a [much later release](https://github.com/cengelha/NomNom/blob/3.0.0.13-alpha.13/ROADMAP.md#alpha19---importexport-raw-json) but I already experimented with it and that's why it's already there but not functional.
All features that are not implemented will be hidden in the future, instead of simply disabling them, for less confusion.

**Comment by LegitSoulja** [comment]
Why has this taken over a year?

**Comment by cengelha** [comment]
@LegitSoulja Because I do this in my free time, wasn't able develop NomNom further for about half a year (shortly after this was opened), and when I picked it up again there were other priorities to do first.

**Comment by LegitSoulja** [comment]
> @LegitSoulja Because I do this in my free time, wasn't able develop NomNom further for about half a year (shortly after this was opened), and when I picked it up again there were other priorities to do first.

It would be nice if you released the source, that way people like I could atleast help contribute if you have less time on your hands.

For now though I have re/compiled a fix for this.
