### ISSUE TITLE
[Bug] Crash on Startup

### ISSUE THREAD

**Issue by Helgrave** [cengelha/NomNom#45]
### Description
Application crashes at runtime with the error: "The invocation of the constructor on type 'NomNom.ViewModel.MainViewModel' that matches the specified binding constraints threw an exception."
This started happening after I attempted to run the save editor while the game was still running (Stupid, I know).
The save itself seems to still work fine as I am able to run the game and continue to play without issue.

Crash Reports: 
[CrashReports.zip](https://github.com/cengelha/NomNom/files/6417493/CrashReports.zip)

### Steps to Reproduce
1. Run NomNom.exe
2. Crash happens immediately.
Rebooting computer does not solve.

### Expected Behavior
Application runs and allows for editing of save file.

### Actual Behavior
Application crashes with the following error: "The invocation of the constructor on type 'NomNom.ViewModel.MainViewModel' that matches the specified binding constraints threw an exception."

### Basic Information

- Version with issue: 3.1.0.15-alpha.15
- Platform you use: Windows 10 Pro

### Screenshots

![image](https://user-images.githubusercontent.com/83612699/116928542-3a807380-ac2b-11eb-99ec-0a1083be2e28.png)

**Comment by Helgrave** [comment]
As an update to this, I was able to replicate this issue on both the MSFT Store and Steam versions of the game.
Same process, if the Save Editor is ran while the game has a save loaded, or if you simply forget to close the save editor before running the game, this same crash will occur the next time you attempt o run the Save Editor.

**Comment by officialfatjesus** [comment]
Same issue here. Doesn't seem to be any developer response to this issue.

**Comment by cengelha** [comment]
@officialfatjesus Just because I don't comment on each issue, or update it with its progress, it doesn't mean it will not be addressed ;) I get notifications for every post in every issue.
Please be a bit more patient until the next version is ready.

Also please don't create another issue with the exact same problem. Especially if you know this issue exists. The message alone doesn't help either. If it crashes, add the report as Helgrave did as I don't have a clue what happened otherwise (except it crashed).
